### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [leahbaker116/prj-rev-bwfs-dasmoto#5]
https://github.com/leahbaker116/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20and%20Crafts/style.css#L10-L32

You've missed a lot of opportunities here to reduce the repetition in your stylesheet. 

These three rules are practically the same except for the background-color, so you should take advantage of this and consolidate the majority of these rules into their own rule with multiple selectors.

```css
.frames, .brushes, .paint {
  font-size: 32px;
  font-weight: bold;
  color: white;
}
```

Notice I didn't include the font-family. This is also getting repeated excessively in every single rule you've written. Since all the text has the same font, just move it into a rule with the universal selector `*`.

```css
* {
  font-family: Helvetica;
}
```

Now you're ready to remove these styles from the rules you've written, and remove some rules altogether.
